DROP TABLE IF EXISTS "booking" CASCADE;
DROP TABLE IF EXISTS "flight_booking" CASCADE;
DROP TABLE IF EXISTS "room_booking" CASCADE;
DROP TABLE IF EXISTS "car_booking" CASCADE;
DROP TABLE IF EXISTS "flight" CASCADE;
DROP TABLE IF EXISTS "room" CASCADE;
DROP TABLE IF EXISTS "hotel" CASCADE;
DROP TABLE IF EXISTS "car" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "role" CASCADE;
DROP TABLE IF EXISTS "city" CASCADE;
DROP TABLE IF EXISTS "airline_company" CASCADE;

CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstname" varchar(30),
  "lastname" varchar(50),
  "email" varchar(100),
  "password" varchar(100),
  "date_of_birth" date,
  "created_at" timestamp,
  "role_id" integer
);

CREATE TABLE "role" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30)
);

CREATE TABLE "booking" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "flight_booking_id" integer,
  "room_booking_id" integer,
  "car_booking_id" integer,
  "created_at" timestamp,
  "status" varchar(20)
);

CREATE TABLE "flight_booking" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nb_passagers" integer,
  "ob_flight_id" integer,
  "ib_flight_id" integer,
  "nb_pax" integer,
  "status" varchar(20)
);

CREATE TABLE "flight" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer,
  "dept_time" timestamp,
  "arr_time" timestamp,
  "dep_city_id" integer,
  "arr_city_id" integer,
  "price" numeric(10,2)
);

CREATE TABLE "hotel" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_id" integer,
  "adress" varchar(100),
  "stars" integer,
  "img_path" varchar(50),
  "add_info" json
);

CREATE TABLE "room_booking" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "start_date" timestamp,
  "end_date" timestamp,
  "room_id" integer,
  "status" varchar(20)
);

CREATE TABLE "room" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" integer,
  "price_per_night" numeric(10,2),
  "capacity" integer,
  "hotel_id" integer,
  "statham" json
);

CREATE TABLE "car_booking" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "car_id" integer,
  "start_date" date,
  "end_date" date,
  "city_id" integer,
  "price" numeric(10,2),
  "status" varchar(20)
);

CREATE TABLE "city" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20),
  "country" varchar(30)
);

CREATE TABLE "airline_company" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20)
);

CREATE TABLE "car" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brand" varchar(20),
  "model" varchar(20),
  "price_per_day" numeric(10,2),
  "img_path" varchar(100)
);

ALTER TABLE "booking" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "flight_booking" ADD FOREIGN KEY ("ob_flight_id") REFERENCES "flight" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "flight_booking" ADD FOREIGN KEY ("ib_flight_id") REFERENCES "flight" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "booking" ADD FOREIGN KEY ("room_booking_id") REFERENCES "room_booking" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "hotel" ADD FOREIGN KEY ("city_id") REFERENCES "city" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "flight" ADD FOREIGN KEY ("dep_city_id") REFERENCES "city" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "flight" ADD FOREIGN KEY ("arr_city_id") REFERENCES "city" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "flight" ADD FOREIGN KEY ("company_id") REFERENCES "airline_company" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "booking" ADD FOREIGN KEY ("car_booking_id") REFERENCES "car_booking" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "car_booking" ADD FOREIGN KEY ("city_id") REFERENCES "city" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "room_booking" ADD FOREIGN KEY ("room_id") REFERENCES "room" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "room" ADD FOREIGN KEY ("hotel_id") REFERENCES "hotel" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "car_booking" ADD FOREIGN KEY ("car_id") REFERENCES "car" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "booking" ADD FOREIGN KEY ("flight_booking_id") REFERENCES "flight_booking" ("id") DEFERRABLE INITIALLY IMMEDIATE;
