spring.application.name=Back

# Base de données
spring.datasource.url=jdbc:postgresql://db:5432/DestinationFIPnale
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT

# peut etre généré avec la commande :
# [Convert]::ToBase64String((1..64 | ForEach-Object { [byte](Get-Random -Max 256) }))
jwt.secret=c9/D+0q+kM/X6BPv9PC5c5eg2AAzr3021sKwQBBeB/yYcfKs9ZTgH6i/+7zl2OW7ikYY8fq1BpkiQiiSv0h7mA==
jwt.expiration=86400000