spring.application.name=Back

# Base de données
spring.datasource.url=jdbc:postgresql://db:5432/DestinationFIPnale
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=tmLeuyfTq3jTlfbfExrNxakRx2fUBsAXw93sqHF80aHMf4x/GlZt+lEKRG97uPt5a6AQ4Nnyeb6Gzc9dICB5EQ==
jwt.expiration=86400000