spring.application.name=Back

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/DestinationFIPnale}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# JWT
jwt.secret=${JWT_SECRET:VUgyGs9BfT55mZi94yaJ0UvWfpgyxXgs/76HTy4C7XOULv9VsRir/0TSUNN+JlcvJYTv8zpfO8KRcYSjpmIa/A==}
jwt.expiration=${JWT_EXPIRATION:86400000}
